"""A simple API for creating and using playing cards"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto #0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/00_card.ipynb #f5317c97
suits = ["♣️","♦️","♥️","♠️"]
ranks = [None, "A"] + [str(x) for x in range(2, 11)] + ["J", "Q", "K"]

# %% ../nbs/00_card.ipynb #db5cffc9
class Card:
    "A playing card"
    def __init__(self,
                 suit,   # An index into `suits`
                 rank):  # An index into `ranks`
        self.suit, self.rank = suit, rank
    def __str__(self): return f"{suits[self.suit]}{ranks[self.rank]}"
    __repr__ = __str__
    def __eq__(self, b): return (self.suit, self.rank)==(b.suit, b.rank)
    def __lt__(self, b): return (self.suit, self.rank)<(b.suit, b.rank)
